import { L } from "@/content/helpers";
import type { HtmlHintDefinition } from "./types";

export const HTML_HINTS: HtmlHintDefinition[] = [
  {
    id: "alt",
    title: L("Image alt text", "نص alt للصورة"),
    caption: L(
      "Every image needs alt text. Screen readers read it aloud. Search engines use it too. If the image does not load, users still know what it was. One short sentence per <img> is enough.",
      "كل صورة محتاجة alt — قارئ الشاشة بيقراها، محركات البحث بتفهمها، والمستخدم يعرف الصفحة لو الصورة ماحملتش. جملة صادقة واحدة لكل <img>.",
    ),
    accent: "from-violet-950 via-slate-950 to-cyan-950",
    beats: [
      {
        id: "hook",
        hook: L("No alt?", "من غير alt؟"),
        sub: L("Screen readers skip it", "قارئ الشاشة بيتخطاها"),
        code: '<img src="photo.jpg">',
        codeTone: "bad",
        visual: "broken",
      },
      {
        id: "fix",
        hook: L("Name the image", "سمّي الصورة"),
        sub: L('Add alt="…"', 'حط alt="…"'),
        code: '<img src="photo.jpg" alt="Orange sunset over the sea">',
        codeTone: "good",
        visual: "fixed",
      },
      {
        id: "done",
        hook: L("Now it works", "دلوقتي شغّال"),
        sub: L("alt on every image", "alt على كل صورة"),
        code: '<img src="photo.jpg" alt="Orange sunset over the sea">',
        codeTone: "good",
        visual: "glow",
      },
    ],
  },
  {
    id: "doctype",
    title: L("DOCTYPE first", "DOCTYPE أول سطر"),
    caption: L(
      "The first line of every HTML file should be <!DOCTYPE html>. Without it, the browser uses old layout rules. Padding, width, and flex can break in odd ways.",
      "أول سطر في أي ملف HTML لازم يكون <!DOCTYPE html>. من غيره المتصفح يدخل quirks mode — الـ padding والعرض والـ flex ممكن يتكسروا بطرق غريبة.",
    ),
    accent: "from-slate-950 via-indigo-950 to-slate-950",
    beats: [
      {
        id: "hook",
        hook: L("Line 1 missing?", "السطر الأول ناقص؟"),
        sub: L("Browser uses old rules", "المتصفح بيستخدم قواعد قديمة"),
        code: "<html>\n  <head>…</head>\n</html>",
        codeTone: "bad",
        visual: "quirks",
      },
      {
        id: "fix",
        hook: L("Add DOCTYPE", "حط DOCTYPE"),
        sub: L("<!DOCTYPE html> first", "<!DOCTYPE html> أول سطر"),
        code: "<!DOCTYPE html>\n<html>\n  …\n</html>",
        codeTone: "good",
        visual: "standards",
      },
      {
        id: "done",
        hook: L("Layout works", "التخطيط مظبوط"),
        sub: L("Modern rules on", "القواعد الحديثة شغّالة"),
        code: "<!DOCTYPE html>\n<html lang=\"en\">",
        codeTone: "good",
        visual: "glow",
      },
    ],
  },
  {
    id: "h1",
    title: L("One h1 per page", "h1 واحد للصفحة"),
    caption: L(
      "Use one <h1> per page for the main title. Use <h2> and <h3> for sections below it. This helps screen readers and search engines follow your page.",
      "كل صفحة ليها <h1> واحد — الموضوع الرئيسي. عناوين الأقسام بـ <h2> لحد <h6>. سلم عناوين واضح يساعد قارئ الشاشة والـ SEO.",
    ),
    accent: "from-rose-950 via-slate-950 to-amber-950",
    beats: [
      {
        id: "hook",
        hook: L("Two h1s?", "اتنين h1؟"),
        sub: L("One title per page", "عنوان واحد للصفحة"),
        code: "<h1>Welcome</h1>\n<h1>Sale today</h1>",
        codeTone: "bad",
        visual: "multi-h1",
      },
      {
        id: "fix",
        hook: L("One h1 only", "h1 واحد بس"),
        sub: L("h2 for sections", "h2 للأقسام"),
        code: "<h1>Shop</h1>\n<h2>Summer sale</h2>\n<h3>Shoes</h3>",
        codeTone: "good",
        visual: "ladder",
      },
      {
        id: "done",
        hook: L("Clear structure", "هيكل واضح"),
        sub: L("Good for SEO too", "كويس للـ SEO كمان"),
        code: "<h1>Shop</h1>\n<h2>Summer sale</h2>",
        codeTone: "good",
        visual: "glow",
      },
    ],
  },
  {
    id: "lang",
    title: L("Page language", "لغة الصفحة"),
    caption: L(
      'Add lang and dir on <html>. For Arabic use lang="ar" dir="rtl" so the page reads right to left. Screen readers also pick the right voice from lang.',
      'حط lang و dir على <html>. للعربي استخدم lang="ar" dir="rtl" عشان الصفحة تتقرا من اليمين لليسار. قارئ الشاشة كمان بياخد النطق الصح من lang.',
    ),
    accent: "from-cyan-950 via-slate-950 to-violet-950",
    beats: [
      {
        id: "hook",
        hook: L("Sounds wrong?", "نطق غلط؟"),
        sub: L("Missing lang", "مفيش lang"),
        code: "<html>\n  <body>مرحبا</body>\n</html>",
        codeTone: "bad",
        visual: "no-lang",
      },
      {
        id: "fix",
        hook: L("Add lang", "حط lang"),
        sub: L('lang="ar" · dir="rtl"', 'lang="ar" · dir="rtl"'),
        code: '<html lang="ar" dir="rtl">\n  <body>مرحبا</body>\n</html>',
        codeTone: "good",
        visual: "with-lang",
      },
      {
        id: "done",
        hook: L("Sounds good", "بينطق صح"),
        sub: L("Arabic reads right → left", "العربي من اليمين لليسار"),
        code: '<html lang="ar" dir="rtl">\n  <body>مرحبا</body>\n</html>',
        codeTone: "good",
        visual: "glow",
      },
    ],
  },
  {
    id: "href",
    title: L("Link href", "href للرابط"),
    caption: L(
      "An <a> tag without href is not a real link. It will not go anywhere. Keyboard users cannot use it well. Always add a URL with href.",
      "وسم <a> من غير href مش رابط حقيقي — مش هيروح لمكان، ومش هيفتح تاب، وبيكسر للي بيستخدم الكيبورد. دايمًا حط وجهة.",
    ),
    accent: "from-blue-950 via-slate-950 to-cyan-950",
    beats: [
      {
        id: "hook",
        hook: L("Dead link?", "رابط ميت؟"),
        sub: L("No href", "مفيش href"),
        code: '<a class="link">About us</a>',
        codeTone: "bad",
        visual: "dead-link",
      },
      {
        id: "fix",
        hook: L("Add href", "حط href"),
        sub: L("Add a URL", "حط عنوان"),
        code: '<a href="/about">About us</a>',
        codeTone: "good",
        visual: "live-link",
      },
      {
        id: "done",
        hook: L("Link works", "الرابط شغّال"),
        sub: L("Real link", "رابط حقيقي"),
        code: '<a href="/about">About us</a>',
        codeTone: "good",
        visual: "glow",
      },
    ],
  },
  {
    id: "semantic",
    title: L("Semantic HTML", "HTML دلالي"),
    caption: L(
      "Do not wrap everything in <div>. Use tags like nav, main, header, and footer. Screen readers can jump between sections. Search engines understand your page better.",
      "بدّل جدران <div> المجهولة بـ nav و main و header و footer. المعالم بتخلي قارئ الشاشة يقفز بين الأقسام ومحركات البحث تفهم الصفحة.",
    ),
    accent: "from-emerald-950 via-slate-950 to-teal-950",
    beats: [
      {
        id: "hook",
        hook: L("Div soup?", "حساء div؟"),
        sub: L("Just divs", "div بس"),
        code: "<div class=\"nav\">…</div>\n<div class=\"main\">…</div>",
        codeTone: "bad",
        visual: "divs",
      },
      {
        id: "fix",
        hook: L("Use real tags", "وسوم حقيقية"),
        sub: L("nav · main · footer", "nav · main · footer"),
        code: "<header>…</header>\n<nav>…</nav>\n<main>…</main>\n<footer>…</footer>",
        codeTone: "good",
        visual: "landmarks",
      },
      {
        id: "done",
        hook: L("Easy to scan", "سهل التصفّح"),
        sub: L("Tags have meaning", "كل وسم ليه معنى"),
        code: "<main>\n  <h1>Content</h1>\n</main>",
        codeTone: "good",
        visual: "glow",
      },
    ],
  },
  {
    id: "btn-link",
    title: L("Button vs link", "زر ولا رابط"),
    caption: L(
      "Use <button> for actions on the page — submit a form, open a menu, toggle something. Use <a href> to go to another page. Mixing them up breaks keyboard use and confuses screen readers.",
      "استخدم <button> للإجراءات في الصفحة (إرسال، تبديل، فتح مودال). استخدم <a href> للتنقّل. خلطهم بيكسر الكيبورد ويلخبط قارئ الشاشة.",
    ),
    accent: "from-amber-950 via-slate-950 to-orange-950",
    beats: [
      {
        id: "hook",
        hook: L("Wrong tag?", "عنصر غلط؟"),
        sub: L("Link styled as button", "رابط شكله زر"),
        code: '<a class="btn">Submit order</a>',
        codeTone: "bad",
        visual: "wrong-btn",
      },
      {
        id: "fix",
        hook: L("Pick the right tag", "اختار الصح"),
        sub: L("Action? Use button", "إجراء؟ استخدم button"),
        code: '<button type="submit">Submit order</button>',
        codeTone: "good",
        visual: "right-btn",
      },
      {
        id: "done",
        hook: L("Right tag", "الوسم الصح"),
        sub: L("New page? Use link", "صفحة جديدة؟ استخدم link"),
        code: '<button type="submit">Send</button>\n<a href="/">Home</a>',
        codeTone: "good",
        visual: "glow",
      },
    ],
  },
  {
    id: "charset",
    title: L("UTF-8 charset", "charset UTF-8"),
    caption: L(
      'Put <meta charset="UTF-8"> near the top of <head>, before any visible text. Without it, Arabic, emoji, and accented letters can show as broken characters.',
      'حط <meta charset="UTF-8"> بدري في <head> — قبل أي نص ظاهر. من غيره العربي والإيموجي والحروف المشكّلة ممكن تطلع رموز غريبة.',
    ),
    accent: "from-fuchsia-950 via-slate-950 to-pink-950",
    beats: [
      {
        id: "hook",
        hook: L("Emoji broke?", "الإيموجي بايظ؟"),
        sub: L("Wrong charset", "ترميز غلط"),
        code: "<!-- browser shows: Hello ðŸ˜€ -->",
        codeTone: "bad",
        visual: "garbled",
      },
      {
        id: "fix",
        hook: L("Add UTF-8", "حط UTF-8"),
        sub: L("Put it in <head>", "حطه في head"),
        code: "<head>\n  <meta charset=\"UTF-8\">\n  <title>My site</title>\n</head>",
        codeTone: "good",
        visual: "charset",
      },
      {
        id: "done",
        hook: L("Hello 👋", "أهلاً 👋"),
        sub: L("Arabic and emoji work", "العربي والإيموجي شغّالين"),
        code: '<meta charset="UTF-8">',
        codeTone: "good",
        visual: "glow",
      },
    ],
  },
  {
    id: "lists",
    title: L("Real HTML lists", "قوائم HTML حقيقية"),
    caption: L(
      'Typing "•" in a paragraph is not a list. Use <ul> or <ol> with <li>. Screen readers can say "list, 3 items" and move through each item.',
      "كتابة • في فقرة مش قائمة. استخدم <ul> أو <ol> مع <li> عشان قارئ الشاشة يقول «قائمة، ٣ عناصر» والمستخدم يتنقّل عنصر عنصر.",
    ),
    accent: "from-lime-950 via-slate-950 to-green-950",
    beats: [
      {
        id: "hook",
        hook: L("Fake bullets?", "نقط مزيفة؟"),
        sub: L("Not a real list", "مش قائمة حقيقية"),
        code: "• Apples\n• Oranges\n• Bananas",
        codeTone: "bad",
        visual: "fake-list",
      },
      {
        id: "fix",
        hook: L("Use ul + li", "استخدم ul + li"),
        sub: L("Real HTML tags", "وسوم HTML حقيقية"),
        code: "<ul>\n  <li>Apples</li>\n  <li>Oranges</li>\n  <li>Bananas</li>\n</ul>",
        codeTone: "good",
        visual: "real-list",
      },
      {
        id: "done",
        hook: L("3 items", "٣ عناصر"),
        sub: L("Screen reader lists it", "قارئ الشاشة بيعدّها"),
        code: "<ul>\n  <li>Apples</li>\n  <li>Oranges</li>\n</ul>",
        codeTone: "good",
        visual: "glow",
      },
    ],
  },
  {
    id: "label",
    title: L("Label your inputs", "سمّي حقول الإدخال"),
    caption: L(
      'Every input needs a <label for="id"> that matches the input id. Clicking the label focuses the field. This helps on mobile and with screen readers.',
      'اربط كل input بـ <label for="id"> نفس الـ id. الضغط على الاسم بيركز الحقل — مهم للموبايل وصعوبات الحركة والفورم الواضح.',
    ),
    accent: "from-sky-950 via-slate-950 to-indigo-950",
    beats: [
      {
        id: "hook",
        hook: L("What is this?", "ده إيه؟"),
        sub: L("No label", "مفيش label"),
        code: '<input type="email" placeholder="Email">',
        codeTone: "bad",
        visual: "lonely-input",
      },
      {
        id: "fix",
        hook: L("Add a label", "حط label"),
        sub: L("for matches id", "for يطابق id"),
        code: '<label for="email">Email</label>\n<input id="email" type="email">',
        codeTone: "good",
        visual: "labeled",
      },
      {
        id: "done",
        hook: L("Label clicks work", "الضغط على الاسم شغّال"),
        sub: L("Easier to tap", "أسهل في الضغط"),
        code: '<label for="email">Email</label>\n<input id="email" type="email" name="email">',
        codeTone: "good",
        visual: "glow",
      },
    ],
  },
];

export const HTML_HINT_LAB_IDS = HTML_HINTS.map((h) => `html-hint-${h.id}` as const);
